name: 'ci-revision-artifact'
description: 'Update git with revision and upload packaged build to artifact repo'

inputs:
  working-dir:
    description: 'the project working directory'
    required: true
  version-type:
    description: 'semantic versioning or datehash versioning'
    required: true
    default: 'datehash'
  artifact-repo:
    description: 'which repo to use to upload the build artifact. only supporting artifactory by jfrog at the moment.'
    required: true
    default: 'artifactory'
  artifact-host:
    description: 'the host of the artifact repo (eg. http://localhost:8081/artifactory)'
    required: true
  artifact-path:
    description: 'the repo path to upload the build artifact'
    required: true
  artifact-token: 
    description: 'the artifact host api token'
    required: false

outputs:
  is_updated:
    description: 'informs if the update was done successfully or not'

runs:
  using: node16
  main: dist/index.js

branding:
  color: 'blue'
  icon: 'archive'