name: 'ci-revision-artifact'
description: 'Update git with revision and upload packaged build to artifact repo'

inputs:
  working-dir:
    description: 'the project working directory'
    required: true
  version-type:
    description: 'semantic versioning or datehash versioning'
    required: true
    default: 'datehash'
  artifact-repo:
    description: 'which repo to use to upload the build artifact. only supporting artifactory by jfrog at the moment.'
    required: true
    default: 'artifactory'

outputs:
  is_updated:
    description: 'informs if the update was done successfully or not'

runs:
  using: node16
  main: dist/index.js

branding:
  color: 'blue'
  icon: 'archive'