name: 'ci-revision-artifact'
description: 'Update git with revision and upload packaged build to artifact repo'

inputs:
  working-dir:
    description: 'The project working directory'
    required: true
  version-type:
    description: 'Semantic versioning or datehash versioning'
    required: true
    default: 'datehash'
  artifact-repo:
    description: '"artifactory" (only supporting artifactory by jfrog for now)'
    required: false
    default: 'artifactory'
  artifact-host:
    description: 'The host of the artifact repo (eg. http://localhost:8081/artifactory)'
    required: true
  artifact-path:
    description: 'The repo path to upload the build artifact'
    required: true
  packager-type: 
    description: 'Define if it is a "zip" or "tar" package. If no value provided it will be defaulted to "zip"'
    require: false
    default: 'zip'
  artifact-token: 
    description: 'The artifact host api token. Not needed if username/password is set'
    required: false
  artifact-username:
    description: 'The artifact repo service username. Not needed if token is set'
    required: false
  artifact-password:
    description: 'The artifact repo service password. Not needed if token is set'
    required: false
  main-branch: 
    description: 'The idenfier of which will be the main git repo branch that will be use for production release. Only needed if you wist to have different name of production vs non-production artifact.'
    required: false
  artifact-postfix: 
    description: 'The postfix that will be use for non-production artifact if "main-branch" is configured. If no value is set here it will default to standard naming.'
    required: false
  extra-artifact-files:
    description: 'The files that will be uploaded as artifacts other than "build.<extension>". Multiple artifacts must be "," seperated (eg. "asset.tar, script.sh"). Default would be "build.<ext>" if no value is provided.'
    required: false

outputs:
  is_updated:
    description: 'informs if the update was done successfully or not'

runs:
  using: node16
  main: dist/index.js

branding:
  color: 'blue'
  icon: 'archive'